# Setup
title:               Hyein Cho
google_analytics_id: UA-234196247-1

# Author
author:
  name:              Hyein Cho
  url:               
  email:             
  selfie: assets/profile_circle.png
  
# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# Custom vars
theme: minima
markdown: kramdown
version:             1.1.0


# # Assets
# # sass:
# #   sass_dir: _sass
# #   style: compressed
